services:

  postgres-demo-db:
    image: postgres:17
    container_name: postgres-demo
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_db
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "listen_addresses=0.0.0.0"]

  pgadmin-demo:
    image: dpage/pgadmin4
    container_name: pgadmin-demo
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  db_data:
  pgadmin_data: